development:
  adapter: postgresql
  database: bookmarks_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bookmarks_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bookmarks_production
  pool: 5
  timeout: 5000